/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    '/admin/topics': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List all topics */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            topic_id: string;
                            /** Format: uuid */
                            parent_topic_id: string | null;
                            label: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        label: string;
                        /** Format: uuid */
                        parent_topic_id?: string | null;
                    };
                };
            };
            responses: {
                /** @description Created topic */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            topic_id: string;
                            /** Format: uuid */
                            parent_topic_id: string | null;
                            label: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/topics/generate': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        context: string;
                    };
                };
            };
            responses: {
                /** @description Topics generated and inserted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/topics/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Topic deleted */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/dataset': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List all questions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            question_id: string;
                            active: boolean;
                            title: string;
                            question:
                                | {
                                      /** @enum {string} */
                                      type: 'multiple_choice';
                                      prompt: string;
                                      answers: string[];
                                  }
                                | {
                                      /** @enum {string} */
                                      type: 'open_ended';
                                      prompt: string;
                                  }
                                | {
                                      /** @enum {string} */
                                      type: 'boolean';
                                      prompt: string;
                                  }
                                | {
                                      /** @enum {string} */
                                      type: 'matching';
                                      prompt: string;
                                      left: string[];
                                      right: string[];
                                  };
                            answer:
                                | {
                                      explanation: string | null;
                                      /** @enum {string} */
                                      type: 'multiple_choice';
                                      selected_index: number[];
                                  }
                                | {
                                      explanation: string | null;
                                      /** @enum {string} */
                                      type: 'open_ended';
                                      answer: string;
                                  }
                                | {
                                      explanation: string | null;
                                      /** @enum {string} */
                                      type: 'boolean';
                                      answer: boolean;
                                  }
                                | {
                                      explanation: string | null;
                                      /** @enum {string} */
                                      type: 'matching';
                                      pairs: {
                                          left_index: number;
                                          right_index: number;
                                      }[];
                                  };
                            topic_ids: string[];
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/dataset/generate': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        prompt: string;
                    };
                };
            };
            responses: {
                /** @description Generation job accepted */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            job_id: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/admin/dataset/jobs': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List all generation jobs */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            job_id: string;
                            /** @enum {string} */
                            status: 'running' | 'done' | 'error';
                            prompt: string;
                            created_at: string;
                            total: number;
                            completed: number;
                            error?: string;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/auth/signup': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        username: string;
                    };
                };
            };
            responses: {
                /** @description Student created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            student_id: string;
                        };
                    };
                };
                /** @description Username already taken */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/auth/login': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        username: string;
                    };
                };
            };
            responses: {
                /** @description Logged in */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            student_id: string;
                        };
                    };
                };
                /** @description Student not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/exams/create': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        prompt: string;
                        /** Format: uuid */
                        student_id: string;
                    };
                };
            };
            responses: {
                /** @description Exam created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            exam_id: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/exams': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query: {
                    student_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description List exams for student */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            exam_id: string;
                            exam_title: string;
                            created_at: string;
                            started_at: string | null;
                            submitted_at: string | null;
                            graded_at: string | null;
                            grade: number | null;
                            /** @enum {string} */
                            status: 'created' | 'started' | 'submitted' | 'graded';
                            question_count: number;
                        }[];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/exams/{id}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Exam detail */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            exam_id: string;
                            exam_title: string;
                            /** Format: uuid */
                            student_id: string;
                            created_at: string;
                            started_at: string | null;
                            submitted_at: string | null;
                            graded_at: string | null;
                            grade: number | null;
                            /** @enum {string} */
                            status: 'created' | 'started' | 'submitted' | 'graded';
                            questions: {
                                /** Format: uuid */
                                question_id: string;
                                question:
                                    | {
                                          /** @enum {string} */
                                          type: 'multiple_choice';
                                          prompt: string;
                                          answers: string[];
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'open_ended';
                                          prompt: string;
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'boolean';
                                          prompt: string;
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'matching';
                                          prompt: string;
                                          left: string[];
                                          right: string[];
                                      };
                                student_answer?:
                                    | {
                                          /** @enum {string} */
                                          type: 'multiple_choice';
                                          selected_index: number[];
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'open_ended';
                                          answer: string;
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'boolean';
                                          answer: boolean;
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'matching';
                                          pairs: {
                                              left_index: number;
                                              right_index: number;
                                          }[];
                                      };
                                reported_at: string | null;
                                correct_answer?:
                                    | {
                                          explanation: string | null;
                                          /** @enum {string} */
                                          type: 'multiple_choice';
                                          selected_index: number[];
                                      }
                                    | {
                                          explanation: string | null;
                                          /** @enum {string} */
                                          type: 'open_ended';
                                          answer: string;
                                      }
                                    | {
                                          explanation: string | null;
                                          /** @enum {string} */
                                          type: 'boolean';
                                          answer: boolean;
                                      }
                                    | {
                                          explanation: string | null;
                                          /** @enum {string} */
                                          type: 'matching';
                                          pairs: {
                                              left_index: number;
                                              right_index: number;
                                          }[];
                                      };
                                grade?: number | null;
                                grading_comment?: string | null;
                            }[];
                        };
                    };
                };
                /** @description Exam not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/exams/{id}/start': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Exam started */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            exam_id: string;
                            exam_title: string;
                            /** Format: uuid */
                            student_id: string;
                            created_at: string;
                            started_at: string | null;
                            submitted_at: string | null;
                            graded_at: string | null;
                            grade: number | null;
                            /** @enum {string} */
                            status: 'created' | 'started' | 'submitted' | 'graded';
                            questions: {
                                /** Format: uuid */
                                question_id: string;
                                question:
                                    | {
                                          /** @enum {string} */
                                          type: 'multiple_choice';
                                          prompt: string;
                                          answers: string[];
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'open_ended';
                                          prompt: string;
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'boolean';
                                          prompt: string;
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'matching';
                                          prompt: string;
                                          left: string[];
                                          right: string[];
                                      };
                                student_answer?:
                                    | {
                                          /** @enum {string} */
                                          type: 'multiple_choice';
                                          selected_index: number[];
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'open_ended';
                                          answer: string;
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'boolean';
                                          answer: boolean;
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'matching';
                                          pairs: {
                                              left_index: number;
                                              right_index: number;
                                          }[];
                                      };
                                reported_at: string | null;
                                correct_answer?:
                                    | {
                                          explanation: string | null;
                                          /** @enum {string} */
                                          type: 'multiple_choice';
                                          selected_index: number[];
                                      }
                                    | {
                                          explanation: string | null;
                                          /** @enum {string} */
                                          type: 'open_ended';
                                          answer: string;
                                      }
                                    | {
                                          explanation: string | null;
                                          /** @enum {string} */
                                          type: 'boolean';
                                          answer: boolean;
                                      }
                                    | {
                                          explanation: string | null;
                                          /** @enum {string} */
                                          type: 'matching';
                                          pairs: {
                                              left_index: number;
                                              right_index: number;
                                          }[];
                                      };
                                grade?: number | null;
                                grading_comment?: string | null;
                            }[];
                        };
                    };
                };
                /** @description Exam not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/exams/{id}/submit-answer/{questionId}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    questionId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    'application/json': {
                        answer?:
                            | {
                                  /** @enum {string} */
                                  type: 'multiple_choice';
                                  selected_index: number[];
                              }
                            | {
                                  /** @enum {string} */
                                  type: 'open_ended';
                                  answer: string;
                              }
                            | {
                                  /** @enum {string} */
                                  type: 'boolean';
                                  answer: boolean;
                              }
                            | {
                                  /** @enum {string} */
                                  type: 'matching';
                                  pairs: {
                                      left_index: number;
                                      right_index: number;
                                  }[];
                              };
                    };
                };
            };
            responses: {
                /** @description Answer submitted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/exams/{id}/report/{questionId}': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    questionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Question reported */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            ok: boolean;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    '/exams/{id}/grade': {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Exam submitted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            /** Format: uuid */
                            exam_id: string;
                            exam_title: string;
                            /** Format: uuid */
                            student_id: string;
                            created_at: string;
                            started_at: string | null;
                            submitted_at: string | null;
                            graded_at: string | null;
                            grade: number | null;
                            /** @enum {string} */
                            status: 'created' | 'started' | 'submitted' | 'graded';
                            questions: {
                                /** Format: uuid */
                                question_id: string;
                                question:
                                    | {
                                          /** @enum {string} */
                                          type: 'multiple_choice';
                                          prompt: string;
                                          answers: string[];
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'open_ended';
                                          prompt: string;
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'boolean';
                                          prompt: string;
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'matching';
                                          prompt: string;
                                          left: string[];
                                          right: string[];
                                      };
                                student_answer?:
                                    | {
                                          /** @enum {string} */
                                          type: 'multiple_choice';
                                          selected_index: number[];
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'open_ended';
                                          answer: string;
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'boolean';
                                          answer: boolean;
                                      }
                                    | {
                                          /** @enum {string} */
                                          type: 'matching';
                                          pairs: {
                                              left_index: number;
                                              right_index: number;
                                          }[];
                                      };
                                reported_at: string | null;
                                correct_answer?:
                                    | {
                                          explanation: string | null;
                                          /** @enum {string} */
                                          type: 'multiple_choice';
                                          selected_index: number[];
                                      }
                                    | {
                                          explanation: string | null;
                                          /** @enum {string} */
                                          type: 'open_ended';
                                          answer: string;
                                      }
                                    | {
                                          explanation: string | null;
                                          /** @enum {string} */
                                          type: 'boolean';
                                          answer: boolean;
                                      }
                                    | {
                                          explanation: string | null;
                                          /** @enum {string} */
                                          type: 'matching';
                                          pairs: {
                                              left_index: number;
                                              right_index: number;
                                          }[];
                                      };
                                grade?: number | null;
                                grading_comment?: string | null;
                            }[];
                        };
                    };
                };
                /** @description Exam not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        'application/json': {
                            error: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
